<?php

namespace App\Tests\Message;

use App\Service\FmpApiService;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\MockObject\Stub;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;

class CompanyRequestTest extends KernelTestCase
{
    public static function setUpBeforeClass(): void
    {
        self::bootKernel();
    }

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIfAllLogicOk()
    {
        $container = static::getContainer();
// 1. FmpApiService
        $mockFmpService = $this->createMock(FmpApiService::class);
        $mockFmpService->expects(self::once())
            ->method('getProfile')
            ->willReturn([[
                'symbol' => 'AAPL'
            ]]);
        $container->set(FmpApiService::class, $mockFmpService);

        $service = $container->get(FmpApiService::class);
        $a = $service->getProfile('AAPL');
        dump($a);
        //self::markTestIncomplete();
    }

    public function testIfApiResponseIsNotOk()
    {
        self::markTestIncomplete();
    }


    public function createStub(string $originalClassName): Stub
    {
        return parent::createStub($originalClassName); // TODO: Change the autogenerated stub
    }
}
